///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
///
///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ImageObjectDimensions {
/*
{
  "width": 0,
  "height": 0
} 
*/

  int? width;
  int? height;

  ImageObjectDimensions({
    this.width,
    this.height,
  });
  ImageObjectDimensions.fromJson(Map<String, dynamic> json) {
    width = int.tryParse(json["width"]?.toString() ?? '');
    height = int.tryParse(json["height"]?.toString() ?? '');
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["width"] = width;
    data["height"] = height;
    return data;
  }
}

class ImageObjectPosition {
/*
{
  "x": 0,
  "y": 0
} 
*/

  int? x;
  int? y;

  ImageObjectPosition({
    this.x,
    this.y,
  });
  ImageObjectPosition.fromJson(Map<String, dynamic> json) {
    x = int.tryParse(json["x"]?.toString() ?? '');
    y = int.tryParse(json["y"]?.toString() ?? '');
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["x"] = x;
    data["y"] = y;
    return data;
  }
}

class ImageObject {
/*
{
  "position": {
    "x": 0,
    "y": 0
  },
  "dimensions": {
    "width": 0,
    "height": 0
  },
  "path": ""
} 
*/

  ImageObjectPosition? position;
  ImageObjectDimensions? dimensions;
  String? path;

  ImageObject({
    this.position,
    this.dimensions,
    this.path,
  });
  ImageObject.fromJson(Map<String, dynamic> json) {
    position = (json["position"] != null && (json["position"] is Map))
        ? ImageObjectPosition.fromJson(json["position"])
        : null;
    dimensions = (json["dimensions"] != null && (json["dimensions"] is Map))
        ? ImageObjectDimensions.fromJson(json["dimensions"])
        : null;
    path = json["path"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (position != null) {
      data["position"] = position!.toJson();
    }
    if (dimensions != null) {
      data["dimensions"] = dimensions!.toJson();
    }
    data["path"] = path;
    return data;
  }
}

class GameObjectTextText {
/*
{
  "singular": "Choose one of the following:",
  "plural": ""
} 
*/

  String? singular;
  String? plural;

  GameObjectTextText({
    this.singular,
    this.plural,
  });
  GameObjectTextText.fromJson(Map<String, dynamic> json) {
    singular = json["singular"]?.toString();
    plural = json["plural"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data["singular"] = singular;
    data["plural"] = plural;
    return data;
  }
}

class GameObjectTextPosition {
/*
{
  "x": 0.1,
  "y": 0.15
} 
*/

  double? x;
  double? y;

  GameObjectTextPosition({
    this.x,
    this.y,
  });
  GameObjectTextPosition.fromJson(Map<String, dynamic> json) {
    x = double.tryParse(json["x"]?.toString() ?? '');
    y = double.tryParse(json["y"]?.toString() ?? '');
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data["x"] = x;
    data["y"] = y;
    return data;
  }
}

class GameObjectText {
/*
{
  "position": {
    "x": 0.1,
    "y": 0.15
  },
  "text": {
    "singular": "Choose one of the following:",
    "plural": ""
  },
  "centered": false,
  "size": "Medium"
} 
*/

  GameObjectTextPosition? position;
  GameObjectTextText? text;
  bool? centered;
  String? size;

  GameObjectText({
    this.position,
    this.text,
    this.centered,
    this.size,
  });
  GameObjectText.fromJson(Map<String, dynamic> json) {
    position = (json["position"] != null && (json["position"] is Map))
        ? GameObjectTextPosition.fromJson(json["position"])
        : null;
    text = (json["text"] != null && (json["text"] is Map))
        ? GameObjectTextText.fromJson(json["text"])
        : null;
    centered = json["centered"];
    size = json["size"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    if (position != null) {
      data["position"] = position!.toJson();
    }
    if (text != null) {
      data["text"] = text!.toJson();
    }
    data["centered"] = centered;
    data["size"] = size;
    return data;
  }
}

class GameObjectDimensions {
/*
{
  "width": 0,
  "height": 0
} 
*/

  int? width;
  int? height;

  GameObjectDimensions({
    this.width,
    this.height,
  });
  GameObjectDimensions.fromJson(Map<String, dynamic> json) {
    width = int.tryParse(json["width"]?.toString() ?? '');
    height = int.tryParse(json["height"]?.toString() ?? '');
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data["width"] = width;
    data["height"] = height;
    return data;
  }
}

class GameObjectPosition {
/*
{
  "x": 0,
  "y": 0
} 
*/

  int? x;
  int? y;

  GameObjectPosition({
    this.x,
    this.y,
  });
  GameObjectPosition.fromJson(Map<String, dynamic> json) {
    x = int.tryParse(json["x"]?.toString() ?? '');
    y = int.tryParse(json["y"]?.toString() ?? '');
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data["x"] = x;
    data["y"] = y;
    return data;
  }
}

class GameObject {
/*
{
  "position": {
    "x": 0,
    "y": 0
  },
  "dimensions": {
    "width": 0,
    "height": 0
  },
  "order": "InOut",
  "text": {
    "position": {
      "x": 0.1,
      "y": 0.15
    },
    "text": {
      "singular": "Choose one of the following:",
      "plural": ""
    },
    "centered": false,
    "size": "Medium"
  },
  "is_option": false
} 
*/

  GameObjectPosition? position;
  GameObjectDimensions? dimensions;
  String? order;
  GameObjectText? text;
  bool? isOption;
  bool? isCorrect;

  GameObject(
      {this.position,
      this.dimensions,
      this.order,
      this.text,
      this.isOption,
      this.isCorrect});
  GameObject.fromJson(Map<String, dynamic> json) {
    position = (json["position"] != null && (json["position"] is Map))
        ? GameObjectPosition.fromJson(json["position"])
        : null;
    dimensions = (json["dimensions"] != null && (json["dimensions"] is Map))
        ? GameObjectDimensions.fromJson(json["dimensions"])
        : null;
    order = json["order"]?.toString();
    text = (json["text"] != null && (json["text"] is Map))
        ? GameObjectText.fromJson(json["text"])
        : null;
    isOption = json["is_option"];
    isCorrect = json["is_correct"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    if (position != null) {
      data["position"] = position!.toJson();
    }
    if (dimensions != null) {
      data["dimensions"] = dimensions!.toJson();
    }
    data["order"] = order;
    if (text != null) {
      data["text"] = text!.toJson();
    }
    data["is_option"] = isOption;
    data["is_correct"] = isCorrect;

    return data;
  }
}
